<?php
/**
 * Eleven registration committees: type slug => [ label_en, label_ar, questions[] ]
 * Questions are 1-based item_index; last item is usually "Accordingly, the committee considers the student"
 */
return [
    'speech_specialist' => [
        'label_en' => 'Speech Specialist Committee',
        'label_ar' => 'لجنة أخصائي التخاطب',
        'questions' => [
            1 => 'Problems during pregnancy',
            2 => 'Problems during delivery',
            3 => 'Attention',
            4 => 'Eye contact',
            5 => 'Imitation',
            6 => 'Expressive language',
            7 => 'Receptive language',
            8 => 'Recognizing surrounding objects',
            9 => 'Recognizing vegetables',
            10 => 'Recognizing fruit',
            11 => 'Recognizing animals',
            12 => 'Recognizing colors',
            13 => 'Recognizing means of transportation',
            14 => 'Recognizing body parts and their functions',
            15 => 'Does the child need speech therapy?',
            16 => 'Accordingly, the committee considers the student',
        ],
    ],
    'medical' => [
        'label_en' => 'Medical Committee',
        'label_ar' => 'اللجنة الطبية',
        'questions' => [
            1 => 'Heart disease',
            2 => 'Kidney disease',
            3 => 'Chronic disease (e.g., diabetes)',
            4 => 'History of convulsions',
            5 => 'Vision weakness',
            6 => 'Chest allergy',
            7 => 'Skin allergy',
            8 => 'Deformities in hand/foot bones',
            9 => 'Hereditary diseases',
            10 => 'Anemia',
            11 => 'Muscle weakness or atrophy',
            12 => 'Allergy to any specific medication',
            13 => 'Can the child use the school clinic for first aid',
            14 => 'Language development',
            15 => 'Chronological age aligned with mental age',
            16 => 'Responds to presented aids',
            17 => 'Special abilities; needs IQ test',
            18 => 'Accordingly, the committee considers the student',
        ],
    ],
    'behavior_quran' => [
        'label_en' => 'Behavior Committee (Holy Qur\'an)',
        'label_ar' => 'لجنة السلوك (القرآن الكريم)',
        'questions' => [
            1 => 'Letter pronunciation',
            2 => 'Ability to recite Surah Al-Fatiha',
            3 => 'Recognizing wudu (ablution) pictures',
            4 => 'Recognizing some behaviors',
            5 => 'Language development',
            6 => 'Chronological age aligned with mental age',
            7 => 'Responds to presented aids',
            8 => 'Special abilities; needs IQ test',
            9 => 'Accordingly, the committee considers the student',
        ],
    ],
    'educational' => [
        'label_en' => 'Educational Committee',
        'label_ar' => 'اللجنة التربوية',
        'questions' => [
            1 => 'Articulation of letters & clear pronunciation',
            2 => 'Recognizing body parts',
            3 => 'Recognizing family members',
            4 => 'Recognizing vegetables and fruit',
            5 => 'Matching a shape with its shadow',
            6 => 'Motor coordination ability',
            7 => 'Good interaction with adults',
            8 => 'Child\'s response with the teacher',
            9 => 'Identify color',
            10 => 'Identify birds',
            11 => 'Identify Animals',
            12 => 'Language development',
            13 => 'Chronological age aligned with mental age',
            14 => 'Responds to presented aids',
            15 => 'Accordingly, the committee considers the student',
        ],
    ],
    'parent_guardian' => [
        'label_en' => 'Parent/Guardian Committee',
        'label_ar' => 'لجنة ولي الأمر',
        'questions' => [
            1 => 'Do both parents work?',
            2 => 'Do you spend time alone with your child—what do you do?',
            3 => 'Do you live in a nuclear family or shared/extended family?',
            4 => 'How do you describe your child\'s nature?',
            5 => 'Why did you choose this school specifically?',
            6 => 'Have you ever punished your child? Why and how?',
            7 => 'What do you expect the school to provide for your child?',
            8 => 'How many hours does your child watch TV?',
            9 => 'What channels are preferred and forbidden?',
            10 => 'What are the child\'s talents and how do you develop them?',
            11 => 'Child\'s strengths and weaknesses (parents\' view)?',
            12 => 'Can you leave work and come to school if asked?',
            13 => 'What do parents do when the child makes a mistake or repeats it?',
            14 => 'How do you spend the weekend holiday?',
            15 => 'What do you know about our school?',
            16 => 'How do you punish your child if he does something wrong?',
            17 => 'How many hours do you work, and who looks after your child when he returns?',
            18 => 'Has your child attended nursery before?',
            19 => 'What is your child\'s daily routine?',
            20 => 'How does the child accept punishment?',
            21 => 'What time does the child go to sleep?',
            22 => 'Accordingly, the committee considers the student',
        ],
    ],
    'stage_deputy' => [
        'label_en' => 'Stage Deputy',
        'label_ar' => 'نائب المرحلة',
        'questions' => [
            1 => 'Stage deputy\'s opinion on accepting the student',
            2 => 'Accordingly, I consider the student',
        ],
        'has_opinion' => true,
    ],
    'social_worker' => [
        'label_en' => 'Social Worker Specialist Committee',
        'label_ar' => 'لجنة الأخصائي الاجتماعي',
        'questions' => [
            1 => 'General appearance',
            2 => 'Child\'s eye contact',
            3 => 'Child\'s verbal communication',
            4 => 'Ability to focus and pay attention',
            5 => 'Response to complex commands',
            6 => 'Ability to express himself',
            7 => 'Awareness of surrounding environment',
            8 => 'Problem-solving ability',
            9 => 'Ability to acquire information',
            10 => 'Interaction with examiner and general behavior',
            11 => 'Accordingly, I consider the student',
        ],
    ],
    'music' => [
        'label_en' => 'Music Committee',
        'label_ar' => 'لجنة الموسيقى',
        'questions' => [
            1 => 'Child\'s inclination toward instruments',
            2 => 'Child can sing alone',
            3 => 'Can imitate some simple rhythms (band instruments)',
            4 => 'Recognizes names of some instruments',
            5 => 'Language development',
            6 => 'Chronological age aligned with mental age',
            7 => 'Responds to presented aids',
            8 => 'Special abilities; needs IQ test',
            9 => 'Accordingly, the committee considers the student',
        ],
    ],
    'physical_education' => [
        'label_en' => 'Physical Education Committee',
        'label_ar' => 'لجنة التربية الرياضية',
        'questions' => [
            1 => 'Throw/aim the ball to the farthest distance',
            2 => 'Speed of collecting similar balls (three colors in least time)',
            3 => 'Throw/aim at wooden boards',
            4 => 'Run with the ball for a certain distance in the least time',
            5 => 'Jump over obstacles (counters/cones)',
            6 => 'Zigzag running',
            7 => 'Language development',
            8 => 'Chronological age aligned with mental age',
            9 => 'Responds to presented aids',
            10 => 'Special abilities; needs IQ test',
            11 => 'Accordingly, the committee considers the student',
        ],
    ],
    'activity' => [
        'label_en' => 'Activity Committee',
        'label_ar' => 'لجنة النشاط',
        'questions' => [
            1 => 'Recognizing colors',
            2 => 'Ability to model with clay',
            3 => 'Ability to assemble and disassemble',
            4 => 'Points to the locations of objects and their places',
            5 => 'Ability to color',
            6 => 'Ability to draw',
            7 => 'Language development',
            8 => 'Chronological age aligned with mental age',
            9 => 'Responds to presented aids',
            10 => 'Special abilities; needs IQ test',
            11 => 'Accordingly, the committee considers the student',
        ],
    ],
    'behavior_christian' => [
        'label_en' => 'Behavior Committee (Christian Religion)',
        'label_ar' => 'لجنة السلوك (الدين المسيحي)',
        'questions' => [
            1 => 'Knowing/recognizing the drawing of the cross',
            2 => 'Ability to recite part of the Lord\'s Prayer',
            3 => 'Recognizing pictures of some saints',
            4 => 'Ability to repeat verses',
            5 => 'Ability to recite part of a hymn',
            6 => 'Language development',
            7 => 'Chronological age aligned with mental age',
            8 => 'Response to presented aids/materials',
            9 => 'Child has special abilities and needs an IQ test',
            10 => 'Accordingly, the committee considers the student',
        ],
    ],
];
